### ISSUE TITLE
ReferenceError: process is not defined

### ISSUE THREAD

**Issue by Jaydeep189** [mklef121/react-tailwind-table#42]
My project is a vite react app, with tailwindcss

below is the simple code of rendering table

I don't know what it's not working

````
import Table from "react-tailwind-table";
import "react-tailwind-table/dist/index.css";

export default function TableTailwind() {
  return <Table columns={[]} rows={[]} />;
}
````

**Comment by ValerioBob** [comment]
Identical setup and error:

Uncaught ReferenceError: process is not defined
    at i2 (factoryWithTypeCheckers.js:170:9)
    at l2 (factoryWithTypeCheckers.js:241:12)
    at factoryWithTypeCheckers.js:116:12
    at factoryWithTypeCheckers.js:590:10
    at a (react-tailwind-table.js?v=3402fe69:26:10)
    at factoryWithThrowingShims.js:16:1

**Comment by curtizdev** [comment]
I am currently experiencing the same issue with the library, using CRA.

**Comment by blackranja** [comment]
Same Here i installed forcefully and when i run it, Uncaught ReferenceError: process is not defined
